
#ansible-playbook -i ./ansible/hosts.ini ./ansible/clone.yml  -e secret.yml  --user=github_ansible_lamanu  -vv   --ask-vault-password

- name: Git Private Repository && Docker Container
  hosts: all
  gather_facts: false
  become: no
  tasks:



  - name: Clone a private repository into .depot.
    vars:
      git:
        token: '{{ lookup("env", "PAT") }}'
    git:
      #repo: https://github.com/fabstock/notes-manager
      #repo: git:${PAT}@github.com:fabstock/notes-manager.git
      repo: https://${PAT}@github.com/fabstock/notes-manager.git
      #version: master
      dest:  ./deploy/
      #single_branch: 
      #key_file:
      #separate_git_dir: notes_manager_dev
      accept_hostkey: yes
      clone: yes
      update: yes
    # ssh-agent doesn't allow key to pass through remote sudo commands.
    become: no


