- name: Deploy Docker Container
  hosts: all
  gather_facts: false
  become: no
  tasks:

  - name: Create Network  Docker 
    shell: |
      if [ -z "$(docker network ls --filter name=^notes-manager$ --format '{{'{{'}}.Name{{'}}'}}' )" ];then
        echo docker network create  --subnet "172.19.0.0/24" notes-manager
      else
        echo 'docker network exist'
      fi
    args:
      executable: /bin/bash
    register: docker_network

  - name:  Checkout dev branch  
    shell: cd deploy && git checkout dev  && git ls-files 

  - name:  Down the docker compose  one image 
    shell: cd deploy docker compose --env-file  Docker/.env_prod -f Docker/docker-compose-one-image.yml  down || echo 0 

  - name:  Launch the docker compose  one image 
    shell: cd deploy && docker compose --env-file  Docker/.env_prod -f Docker/docker-compose-one-image.yml -f Docker/docker-compose-nginx.yml  up  -d 

 



