- name: Prepare and down Docker Container
  hosts: all
  gather_facts: false
  become: no
  tasks:

  - name: launch docker compose
    shell: echo $(date)

  - name: launch the docker 
    shell: docker ps -a



  - name:  Check if deploy exists
    shell: |
      if [ -d  "deploy" ];then
          echo "Old deployement detecté   down & downdeploy "
          cd deploy  && docker compose --env-file  Docker/.env_prod -f Docker/docker-compose-one-image.yml -f Docker/docker-compose-nginx.yml  down || echo 0
          cd .. && rm -rf deploy || echo 0
      else
          echo "first deployement"
      fi
  
  - name: Create Network  Docker
    shell: |
      if [ ! -z "$(docker network ls --filter name=^notes-manager$ --format '{{'{{'}}.Name{{'}}'}}' )" ];then
        #docker network create  --subnet "10.90.90.0/24" notes-manager
        docker network rm notes-manager
      elif [ ! -z "$(docker network ls --filter name=^notes-manager-frontend$ --format '{{'{{'}}.Name{{'}}'}}' )" ];then
        #docker network create  --subnet "172.19.0.0/24" notes-manager-frontend
        docker network rm notes-manager-frontend
      else  
        echo "docker network don't exist"
      fi
    args:
      executable: /bin/bash
    register: docker_network


  - name: Debug
    ansible.builtin.debug:
      var: docker_network


